/*/
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controllers.AdviceController;
import Controllers.OpenAIClient;
import Models.User;
import java.io.IOException;

/**
 *
 * @author DINHHUNG
 */
public class AdvicePanel extends javax.swing.JPanel {

   private User user;
    public AdvicePanel(User user) {
    this.user=user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        advise = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();

        advise.setBackground(new java.awt.Color(0, 153, 153));
        advise.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        advise.setText("Tư Vấn");
        advise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adviseActionPerformed(evt);
            }
        });

        text.setBackground(new java.awt.Color(255, 204, 153));
        text.setColumns(20);
        text.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(584, 584, 584)
                        .addComponent(advise, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(advise, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adviseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adviseActionPerformed
      
     String data1=new AdviceController().getBudgetsByMonth(user.getId(),"09/2025");
     String data2=new AdviceController().getTransactionsByMonth(user.getId(), "09/2025");
        System.out.println(data1);
        System.out.println(data2);
       try {
           String result=new OpenAIClient().askDeepSeek("đây là dữ liệu"+data1+" "+data2+"hãy đửaa lời khuyên");
           System.out.println(result);
           text.setEditable(false);
           text.setLineWrap(true);        // tự động xuống dòng
           text.setWrapStyleWord(true);   // ngắt tại từ hoàn chỉnh
           text.setText(result);
       } catch (IOException ex) {
           System.getLogger(AdvicePanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
       }
    }//GEN-LAST:event_adviseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advise;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
