/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controllers.CategoryController;
import Controllers.ReportController;
import Models.User;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author DINHHUNG
 */
public class ReportPanel extends javax.swing.JPanel {

    private User user;
    public ReportPanel(User user) {
        this.user=user;
        initComponents();
        setSelectMonthYear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        showReport = new javax.swing.JButton();
        selectMonthReport = new javax.swing.JComboBox<>();
        selectYearReport = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalIncome = new javax.swing.JTextField();
        totalExpense = new javax.swing.JTextField();
        subIncomeExpense = new javax.swing.JTextField();
        overExpense = new javax.swing.JTextField();
        ChartCategoryMonth = new javax.swing.JPanel();
        ChartExpenseMonth = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("Báo Cáo Chi Tiêu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(541, 541, 541)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Chọn Tháng");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Chọn Năm");

        showReport.setBackground(new java.awt.Color(153, 204, 255));
        showReport.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        showReport.setText("Xem Báo Cáo");
        showReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showReportActionPerformed(evt);
            }
        });

        selectMonthReport.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        selectMonthReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectYearReport.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        selectYearReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(selectMonthReport, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectYearReport, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(showReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectMonthReport, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(selectYearReport, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showReport)
                .addGap(14, 14, 14))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Tổng Thu");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Tổng Chi");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Số Dư");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Vượt Mức");

        totalIncome.setBackground(new java.awt.Color(255, 204, 204));
        totalIncome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        totalIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalIncomeActionPerformed(evt);
            }
        });

        totalExpense.setBackground(new java.awt.Color(255, 204, 204));
        totalExpense.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        totalExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalExpenseActionPerformed(evt);
            }
        });

        subIncomeExpense.setBackground(new java.awt.Color(255, 204, 204));
        subIncomeExpense.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        subIncomeExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subIncomeExpenseActionPerformed(evt);
            }
        });

        overExpense.setBackground(new java.awt.Color(255, 204, 204));
        overExpense.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        overExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overExpenseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(totalIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addComponent(subIncomeExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(overExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(overExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(totalIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(totalExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(subIncomeExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))))
        );

        ChartCategoryMonth.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout ChartCategoryMonthLayout = new javax.swing.GroupLayout(ChartCategoryMonth);
        ChartCategoryMonth.setLayout(ChartCategoryMonthLayout);
        ChartCategoryMonthLayout.setHorizontalGroup(
            ChartCategoryMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        ChartCategoryMonthLayout.setVerticalGroup(
            ChartCategoryMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        ChartExpenseMonth.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout ChartExpenseMonthLayout = new javax.swing.GroupLayout(ChartExpenseMonth);
        ChartExpenseMonth.setLayout(ChartExpenseMonthLayout);
        ChartExpenseMonthLayout.setHorizontalGroup(
            ChartExpenseMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        ChartExpenseMonthLayout.setVerticalGroup(
            ChartExpenseMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ChartCategoryMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChartExpenseMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChartCategoryMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChartExpenseMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void totalIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalIncomeActionPerformed

    private void totalExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalExpenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalExpenseActionPerformed

    private void subIncomeExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subIncomeExpenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subIncomeExpenseActionPerformed

    private void overExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overExpenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overExpenseActionPerformed

    private void showReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showReportActionPerformed
          try {
        
        String month = selectMonthReport.getSelectedItem().toString();
        String year = selectYearReport.getSelectedItem().toString();
        String monthYear = year + "-" + month; // ví dụ: "2025-10"

       
        ReportController rc = new ReportController();
        int userId = user.getId();

        
        Map<String, Double> summary = rc.getMonthlySummary(userId, monthYear);
        double income = summary.getOrDefault("income", 0.0);
        double expense = summary.getOrDefault("expense", 0.0);
        double balance = summary.getOrDefault("balance", 0.0);

       
        totalIncome.setText(String.format("%,.0f", income));      
        totalExpense.setText(String.format("%,.0f", expense));
        subIncomeExpense.setText(String.format("%,.0f", balance)); 
      

        
        int vuotMuc = rc.getExceededCount(userId, monthYear);
        overExpense.setText(String.valueOf(vuotMuc));

        
        Map<String, Double> expenseByCat = rc.getExpenseByCategory(userId, monthYear);

       
        ChartCategoryMonth.removeAll();
        ChartExpenseMonth.removeAll();

        if (!expenseByCat.isEmpty()) {
            
            DefaultPieDataset pieDataset = new DefaultPieDataset();
            for (Map.Entry<String, Double> e : expenseByCat.entrySet()) {
                pieDataset.setValue(new CategoryController().getCategoryById(e.getKey()).getName(), e.getValue());
            }

            JFreeChart pieChart = ChartFactory.createPieChart(
                    "Chi tiêu theo danh mục (" + monthYear + ")",
                    pieDataset,
                    true, true, false
            );

            ChartPanel pieChartPanel = new ChartPanel(pieChart);
            ChartCategoryMonth.setLayout(new java.awt.BorderLayout());
            ChartCategoryMonth.add(pieChartPanel, java.awt.BorderLayout.CENTER);

            // Biểu đồ cột: Tổng thu - chi
            DefaultCategoryDataset barDataset = new DefaultCategoryDataset();
            barDataset.addValue(income, "Tổng Thu", month);
            barDataset.addValue(expense, "Tổng Chi", month);

            JFreeChart barChart = ChartFactory.createBarChart(
                    "Tổng thu - chi tháng " + month + "/" + year,
                    "Loại",
                    "Số tiền",
                    barDataset
            );

            ChartPanel barChartPanel = new ChartPanel(barChart);
            ChartExpenseMonth.setLayout(new java.awt.BorderLayout());
            ChartExpenseMonth.add(barChartPanel, java.awt.BorderLayout.CENTER);

        } else {
            // Không có dữ liệu
            ChartCategoryMonth.setLayout(new java.awt.BorderLayout());
            ChartCategoryMonth.add(new JLabel("Không có dữ liệu chi tiêu tháng này.", SwingConstants.CENTER),
                                   java.awt.BorderLayout.CENTER);
        }

        // 🔹 Cập nhật lại UI
        ChartCategoryMonth.revalidate();
        ChartCategoryMonth.repaint();
        ChartExpenseMonth.revalidate();
        ChartExpenseMonth.repaint();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi tạo báo cáo: " + e.getMessage(),
                "Lỗi", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }


    }//GEN-LAST:event_showReportActionPerformed
private void setSelectMonthYear() {
    // 1️⃣ Xóa dữ liệu cũ (nếu có)
    selectMonthReport.removeAllItems();
    selectYearReport.removeAllItems();

    // 2️⃣ Thêm danh sách tháng (01–12)
    for (int i = 1; i <= 12; i++) {
        String month = String.format("%02d", i);
        selectMonthReport.addItem(month);
    }

    // 3️⃣ Lấy năm hiện tại
    java.util.Calendar cal = java.util.Calendar.getInstance();
    int currentYear = cal.get(java.util.Calendar.YEAR);
    int currentMonth = cal.get(java.util.Calendar.MONTH) + 1; // (0-based)

    // 4️⃣ Thêm danh sách năm (ví dụ: 2020 → năm hiện tại)
    for (int y = 2020; y <= currentYear; y++) {
        selectYearReport.addItem(String.valueOf(y));
    }

    // 5️⃣ Đặt mặc định chọn tháng và năm hiện tại
    selectMonthReport.setSelectedItem(String.format("%02d", currentMonth));
    selectYearReport.setSelectedItem(String.valueOf(currentYear));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChartCategoryMonth;
    private javax.swing.JPanel ChartExpenseMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField overExpense;
    private javax.swing.JComboBox<String> selectMonthReport;
    private javax.swing.JComboBox<String> selectYearReport;
    private javax.swing.JButton showReport;
    private javax.swing.JTextField subIncomeExpense;
    private javax.swing.JTextField totalExpense;
    private javax.swing.JTextField totalIncome;
    // End of variables declaration//GEN-END:variables
}
